DROP TABLE JOURNAL;

CREATE TABLE JOURNAL (
ID NUMBER(10,0) NOT NULL AUTO_INCREMENT,
CREATED VARCHAR(255) DEFAULT NULL,
TITLE VARCHAR2(255) DEFAULT NULL,
SUMMARY VARCHAR2(255) DEFAULT NULL,
PRIMARY KEY (ID));

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;
